language: go

go:
  - 1.5.3
  - 1.6
  - tips

before_install:
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls
  - go get -v github.com/golang/lint/golint

install:
  - go get -d -t -v ./...
  - go build -v

script:
  - go test -v ./admin
  - go test -v ./entry
  - go test -v ./queue
  - go test -v ./store
  - go test -v ./utils
  - go test -v .
  - go vet ./...
  - $HOME/gopath/bin/golint ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
